### ISSUE TITLE
Unable to load 3rd-party async script as requirejs module

### ISSUE THREAD

**Issue by julianbolts** [Allov/generator-koco#7]
Hi, I am developing a maps app with your generator, but I am having trouble adding the Google Maps API script properly as a common.js module. I have followed the 'async' trick, mentioned [here](http://blog.millermedeiros.com/requirejs-2-0-delayed-module-evaluation-and-google-maps/), and I added the gmaps module definition to the startup.js, however when I run `gulp --open`, I see that the Google Maps module doesn't load, and neither do dependent modules. 

This is my project: [julianfresco/udacity.frontenddev.p5](https://github.com/julianfresco/udacity.frontenddev.p5)

And I add the module in [this commit](https://github.com/julianfresco/udacity.frontenddev.p5/commit/6a7c1bdba93e0f0d8a7267855c2a12b3bd61f198)

Any tips on getting the Maps API to load properly in the browser?

**Comment by Allov** [comment]
You were so close! The problem isn't that gmaps api isn't loading rather than the component isn't called by knockout, and here's why. The [map tag](https://www.w3.org/wiki/HTML/Elements/map) is a valid HTML markup tag and is therefore ignored by knockout all together. Renaming the component to another name will clear the issue.

[See this commit](https://github.com/Allov/udacity.frontenddev.p5/commit/cd950a42a7d8c088147d7ad876ecf54eb0498f82).

**Comment by julianbolts** [comment]
A-hah... Thank you, Allov, clever crafter of the web! I see this is not a require.js issue, but is a "me vs the W3C" issue! Thanks for the quick reply and suggested fix.
